# Install the AWS CLI
# See https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html
tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT/frontend-react-js
      npm install
      cd $THEIA_WORKSPACE_ROOT
  - name: postgres
    init: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev
      
vscode:
  extensions:
    - 42Crunch.vscode-openapi


ports:
# Expose port 3000 and change visibility to public to access the web application frontend.
  - port: 3000
    visibility: public

# Expose port 4567 change visibility to public for the backend.
  - port: 4567
    visibility: public