# Install the AWS CLI
# See https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html
tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
vscode:
  extensions:
    - 42Crunch.vscode-openapi


ports:
# Expose port 3000 to access the web application frontend.
  - port: 3000
    onOpen: open-preview
    visibility: public

# Expose port 4567 for the backend.
  - port: 4567
    onOpen: ignore
    visibility: public